import { useState } from 'react';
import { Search, Filter, AlertCircle, Clock, MapPin, Building2, Calendar, Zap, Edit2, Plus, X } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { OrderDetailView } from './OrderDetailView';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Label } from './ui/label';
import { Checkbox } from './ui/checkbox';
import { toast } from 'sonner';

interface OrderManagementProps {
  onNavigate: (view: string) => void;
  onAIPlanning: (order: any) => void;
}

export function OrderManagement({ onNavigate, onAIPlanning }: OrderManagementProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null);
  const [editTransportOrder, setEditTransportOrder] = useState<any>(null);
  const [selectedDestinations, setSelectedDestinations] = useState<string[]>([]);
  const [customDestination, setCustomDestination] = useState('');

  // Available destinations list
  const availableDestinations = [
    'Guadalajara',
    'Tijuana',
    'Monterrey',
    'Mexico City',
    'Cancún',
    'Mérida',
    'Querétaro',
    'Puebla',
    'Veracruz',
    'Oaxaca',
    'Mexicali'
  ];

  // Open edit transport dialog
  const handleEditTransport = (order: any) => {
    setEditTransportOrder(order);
    setSelectedDestinations(order.destinations || []);
    setCustomDestination('');
  };

  // Toggle destination selection
  const toggleDestination = (destination: string) => {
    setSelectedDestinations(prev =>
      prev.includes(destination)
        ? prev.filter(d => d !== destination)
        : [...prev, destination]
    );
  };

  // Add custom destination
  const addCustomDestination = () => {
    if (customDestination.trim() && !selectedDestinations.includes(customDestination.trim())) {
      setSelectedDestinations(prev => [...prev, customDestination.trim()]);
      setCustomDestination('');
    }
  };

  // Remove destination
  const removeDestination = (destination: string) => {
    setSelectedDestinations(prev => prev.filter(d => d !== destination));
  };

  // Save transport changes
  const saveTransportChanges = () => {
    if (selectedDestinations.length === 0) {
      toast.error('Please select at least one destination');
      return;
    }
    
    toast.success(`Transport updated for ${editTransportOrder.id} with ${selectedDestinations.length} destination(s)`);
    setEditTransportOrder(null);
  };

  const orders = [
    {
      id: 'ORD-2025-001',
      customerName: 'Customer Central Guadalajara',
      customerCode: 'GDL-001',
      vin: 'VIN001SUV2024, VIN002SUV2024, VIN003SUV2024, VIN004SED2024, VIN005HAT2024, VIN006HAT2024, VIN007SUV2024, VIN008SED2024, VIN009SED2024, VIN010SED2024, VIN011SED2024, VIN012HAT2024, VIN013HAT2024',
      vehicleTypes: [
        { type: 'SUV', quantity: 4 },
        { type: 'Sedan', quantity: 5 },
        { type: 'Hatchback', quantity: 4 }
      ],
      count: 13,
      source: 'Sales Stock',
      yard: 'Yard A - CDMX',
      destinations: ['Guadalajara Dealer'],
      consolidationDeadline: '2025-10-24',
      deliverySLA: '2025-10-28',
      status: 'Ready to dispatch',
      workflowStage: 'route-planned',
      daysLeft: 3,
      autoGenerated: false
    },
    {
      id: 'ORD-2025-002',
      customerName: 'Customer Norte Tijuana',
      customerCode: 'TIJ-001',
      vin: 'VIN456789123, VIN789012345, VIN234567890, VIN345678901, VIN567890123',
      vehicleTypes: [
        { type: 'Sedan', quantity: 3 },
        { type: 'Van Cargo', quantity: 2 }
      ],
      count: 5,
      source: 'Special Order',
      yard: 'Yard B - Monterrey',
      destinations: ['Tijuana'],
      consolidationDeadline: '2025-10-23',
      deliverySLA: '2025-10-27',
      status: 'Pending Confirmation',
      workflowStage: 'confirmed',
      daysLeft: 2,
      autoGenerated: true
    },
    {
      id: 'ORD-2025-003',
      customerName: 'Customer Express Monterrey',
      customerCode: 'MTY-001',
      vin: 'VIN789123456, VIN321654987, VIN654987321, VIN987321654, VIN321987654, VIN654321987, VIN147258369, VIN258369147, VIN369147258, VIN147369258',
      vehicleTypes: [
        { type: 'SUV', quantity: 5 },
        { type: 'Truck', quantity: 3 },
        { type: 'Hatchback', quantity: 2 }
      ],
      count: 10,
      source: 'Yard Stock',
      yard: 'Yard C - Puebla',
      destinations: ['Monterrey', 'Guadalajara', 'Mexico City'],
      consolidationDeadline: '2025-10-22',
      deliverySLA: '2025-10-26',
      status: 'New',
      workflowStage: 'in-preparation',
      daysLeft: 1,
      autoGenerated: false
    },
    {
      id: 'ORD-2025-004',
      customerName: 'AutoGroup Querétaro',
      customerCode: 'QRO-001',
      vin: 'VIN998877665, VIN554433221, VIN112233445, VIN667788990, VIN223344556, VIN778899001, VIN334455667, VIN889900112, VIN445566778, VIN990011223, VIN556677889, VIN101122334',
      vehicleTypes: [
        { type: 'SUV', quantity: 6 },
        { type: 'Sedan', quantity: 4 },
        { type: 'Hatchback', quantity: 2 }
      ],
      count: 12,
      source: 'Sales Stock',
      yard: 'Yard D - Querétaro',
      destinations: ['Querétaro'],
      consolidationDeadline: '2025-10-25',
      deliverySLA: '2025-10-29',
      status: 'New',
      workflowStage: 'confirmed',
      daysLeft: 4,
      autoGenerated: false
    },
    {
      id: 'ORD-2025-005',
      customerName: 'Premium Motors Cancún',
      customerCode: 'CUN-001',
      vin: 'VIN212233445, VIN323344556, VIN434455667, VIN545566778, VIN656677889, VIN767788990, VIN878899001, VIN989900112',
      vehicleTypes: [
        { type: 'SUV', quantity: 5 },
        { type: 'Van Cargo', quantity: 3 }
      ],
      count: 8,
      source: 'Special Order',
      yard: 'Yard A - CDMX',
      destinations: ['Cancún'],
      consolidationDeadline: '2025-10-26',
      deliverySLA: '2025-10-30',
      status: 'Ready to dispatch',
      workflowStage: 'route-planned',
      daysLeft: 5,
      autoGenerated: false
    },
    {
      id: 'ORD-2025-006',
      customerName: 'Fleet Solutions Mérida',
      customerCode: 'MID-001',
      vin: 'VIN121314151, VIN161718192, VIN202122232, VIN242526272, VIN282930313, VIN323334353, VIN363738394, VIN404142434, VIN444546474, VIN484950515',
      vehicleTypes: [
        { type: 'Sedan', quantity: 6 },
        { type: 'Hatchback', quantity: 4 }
      ],
      count: 10,
      source: 'Yard Stock',
      yard: 'Yard B - Monterrey',
      destinations: ['Mérida'],
      consolidationDeadline: '2025-10-24',
      deliverySLA: '2025-10-28',
      status: 'Pending Confirmation',
      workflowStage: 'in-preparation',
      daysLeft: 3,
      autoGenerated: true
    },
  ];

  const autoOrderSuggestions = [
    { yardStock: 'Yard A', vehicles: 5, suggestion: 'Consolidate to Guadalajara route', priority: 'High' },
    { yardStock: 'Yard B', vehicles: 3, suggestion: 'Create Milk Run to Tijuana & Mexicali', priority: 'Medium' },
  ];

  const getStatusBadge = (status: string) => {
    const config: Record<string, { variant: 'default' | 'secondary' | 'destructive' | 'outline', className?: string }> = {
      'New': { variant: 'default', className: 'bg-blue-500' },
      'Pending Confirmation': { variant: 'default', className: 'bg-yellow-500' },
      'Ready to dispatch': { variant: 'default', className: 'bg-green-500' },
    };
    const c = config[status] || { variant: 'outline' as const };
    return <Badge variant={c.variant} className={c.className}>{status}</Badge>;
  };

  const filteredOrders = orders.filter(order => {
    const matchesSearch = 
      order.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      order.vin.toLowerCase().includes(searchQuery.toLowerCase()) ||
      order.customerName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      order.destinations.some(dest => dest.toLowerCase().includes(searchQuery.toLowerCase()));
    
    let matchesStatus = true;
    if (statusFilter === 'new') matchesStatus = order.status === 'New';
    else if (statusFilter === 'pending') matchesStatus = order.status === 'Pending Confirmation';
    else if (statusFilter === 'ready') matchesStatus = order.status === 'Ready to dispatch';
    
    return matchesSearch && matchesStatus;
  });

  // If an order is selected, show detail view
  if (selectedOrderId) {
    return (
      <OrderDetailView 
        orderId={selectedOrderId} 
        onBack={() => setSelectedOrderId(null)} 
      />
    );
  }

  return (
    <div className="h-full">
      {/* Header */}
      <div className="p-6 border-b bg-white">
        <h1 className="text-3xl mb-2">Order & Stock Management</h1>
        <p className="text-gray-600">Manage vehicle orders and consolidation</p>
      </div>

      {/* Auto Order Trigger Panel */}
      <Card className="p-6 mb-6 bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200">
        <div className="flex items-start justify-between mb-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <AlertCircle className="w-5 h-5 text-purple-600" />
              <h2 className="text-xl">Auto Order Suggestions</h2>
              <Badge className="bg-purple-600">AI-Powered</Badge>
            </div>
            <p className="text-sm text-gray-600">Based on daily stock sync and consolidation opportunities</p>
          </div>
          <Button variant="outline" size="sm">
            <Clock className="w-4 h-4 mr-2" />
            Last Sync: 2 hours ago
          </Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {autoOrderSuggestions.map((suggestion, index) => (
            <div key={index} className="bg-white p-4 rounded-lg border border-purple-200">
              <div className="flex items-start justify-between mb-2">
                <div>
                  <p className="font-medium">{suggestion.yardStock}</p>
                  <p className="text-sm text-gray-600">{suggestion.vehicles} vehicles waiting</p>
                </div>
                <Badge variant={suggestion.priority === 'High' ? 'destructive' : 'default'}>
                  {suggestion.priority}
                </Badge>
              </div>
              <p className="text-sm text-gray-700 mb-3">{suggestion.suggestion}</p>
              <Button size="sm" className="w-full bg-purple-600 hover:bg-purple-700">
                Generate Order
              </Button>
            </div>
          ))}
        </div>
      </Card>

      {/* Filters */}
      <Card className="p-4 mb-6">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              placeholder="Search by Order ID, VIN, Destination..."
              className="pl-10"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-full sm:w-48">
              <Filter className="w-4 h-4 mr-2" />
              <SelectValue placeholder="Filter by status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              <SelectItem value="new">New</SelectItem>
              <SelectItem value="pending">Pending Confirmation</SelectItem>
              <SelectItem value="ready">Ready to dispatch</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </Card>

      {/* Orders Table */}
      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Order ID</TableHead>
              <TableHead>VIN List</TableHead>
              <TableHead>Vehicle Types</TableHead>
              <TableHead>Count</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>Yard</TableHead>
              <TableHead>Destinations</TableHead>
              <TableHead>Consolidation Deadline</TableHead>
              <TableHead>Delivery SLA</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredOrders.map((order) => (
              <TableRow 
                key={order.id} 
                className="hover:bg-gray-50"
              >
                <TableCell>
                  <div className="flex items-center gap-2">
                    <span className="font-medium">{order.id}</span>
                    {order.autoGenerated && (
                      <Badge variant="outline" className="text-xs">Auto</Badge>
                    )}
                  </div>
                </TableCell>
                <TableCell>
                  <p className="text-sm truncate max-w-xs" title={order.vin}>
                    {order.vin}
                  </p>
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap gap-1">
                    {order.vehicleTypes.map((vt, idx) => (
                      <Badge key={idx} variant="secondary" className="bg-blue-100 text-blue-800">
                        {vt.type} x{vt.quantity}
                      </Badge>
                    ))}
                  </div>
                </TableCell>
                <TableCell>
                  <Badge variant="secondary">{order.count}</Badge>
                </TableCell>
                <TableCell>{order.source}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-1">
                    <MapPin className="w-3 h-3 text-gray-400" />
                    <span className="text-sm">{order.yard}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap gap-1">
                    {order.destinations.map((dest, idx) => (
                      <Badge key={idx} variant="outline" className="text-xs">
                        {dest}
                      </Badge>
                    ))}
                  </div>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-1">
                    <Calendar className="w-3 h-3 text-gray-400" />
                    <span className="text-sm">{order.consolidationDeadline}</span>
                    {order.daysLeft <= 2 && (
                      <Badge variant="destructive" className="text-xs ml-1">
                        {order.daysLeft}d left
                      </Badge>
                    )}
                  </div>
                </TableCell>
                <TableCell>{order.deliverySLA}</TableCell>
                <TableCell>{getStatusBadge(order.status)}</TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleEditTransport(order);
                      }}
                    >
                      <Edit2 className="w-4 h-4 mr-1" />
                      Edit Transport
                    </Button>
                    <Button 
                      size="sm" 
                      className="bg-purple-600 hover:bg-purple-700"
                      onClick={(e) => {
                        e.stopPropagation();
                        onAIPlanning(order);
                      }}
                    >
                      <Zap className="w-4 h-4 mr-1" />
                      Load Planning
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>

      {/* Edit Transport Dialog */}
      <Dialog open={!!editTransportOrder} onOpenChange={() => setEditTransportOrder(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Edit Transport Destinations</DialogTitle>
            <DialogDescription>
              Select multiple destinations for order {editTransportOrder?.id}
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-6 py-4">
            {/* Current Order Info */}
            {editTransportOrder && (
              <Card className="p-4 bg-blue-50 border-blue-200">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600">Order ID</p>
                    <p className="font-medium">{editTransportOrder.id}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Customer</p>
                    <p className="font-medium">{editTransportOrder.customerName}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Total Vehicles</p>
                    <Badge>{editTransportOrder.count} vehicles</Badge>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Source Yard</p>
                    <p className="font-medium">{editTransportOrder.yard}</p>
                  </div>
                </div>
              </Card>
            )}

            {/* Selected Destinations */}
            {selectedDestinations.length > 0 && (
              <div>
                <Label className="mb-2 block">Selected Destinations ({selectedDestinations.length})</Label>
                <div className="flex flex-wrap gap-2 p-3 bg-green-50 border border-green-200 rounded-lg">
                  {selectedDestinations.map((dest) => (
                    <Badge key={dest} variant="default" className="bg-green-600 flex items-center gap-1">
                      <MapPin className="w-3 h-3" />
                      {dest}
                      <button
                        onClick={() => removeDestination(dest)}
                        className="ml-1 hover:bg-green-700 rounded-full p-0.5"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {/* Available Destinations */}
            <div>
              <Label className="mb-3 block">Available Destinations</Label>
              <div className="grid grid-cols-2 gap-2 max-h-64 overflow-y-auto p-2 border rounded-lg">
                {availableDestinations.map((destination) => (
                  <div key={destination} className="flex items-center space-x-2">
                    <Checkbox
                      id={destination}
                      checked={selectedDestinations.includes(destination)}
                      onCheckedChange={() => toggleDestination(destination)}
                    />
                    <Label
                      htmlFor={destination}
                      className="cursor-pointer flex items-center gap-1"
                    >
                      <MapPin className="w-3 h-3 text-gray-400" />
                      {destination}
                    </Label>
                  </div>
                ))}
              </div>
            </div>

            {/* Add Custom Destination */}
            <div>
              <Label className="mb-2 block">Add Custom Destination</Label>
              <div className="flex gap-2">
                <Input
                  placeholder="Enter custom destination..."
                  value={customDestination}
                  onChange={(e) => setCustomDestination(e.target.value)}
                  onKeyPress={(e) => {
                    if (e.key === 'Enter') {
                      addCustomDestination();
                    }
                  }}
                />
                <Button
                  type="button"
                  onClick={addCustomDestination}
                  disabled={!customDestination.trim()}
                >
                  <Plus className="w-4 h-4 mr-1" />
                  Add
                </Button>
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-end gap-3 pt-4 border-t">
              <Button
                variant="outline"
                onClick={() => setEditTransportOrder(null)}
              >
                Cancel
              </Button>
              <Button
                className="bg-[#E30613] hover:bg-red-700"
                onClick={saveTransportChanges}
              >
                Save Changes
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}